### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by quinnzaballa** [bill-zhanxg/MCPE-Cracker#1]
will this get an update? cause it doesnt work for me.

**Comment by bill-zhanxg** [comment]
> will this get an update? cause it doesnt work for me.

You need to explain how it doesn't work in order for me to fix it

**Comment by quinnzaballa** [comment]
> > will this get an update? cause it doesnt work for me.
> 
> You need to explain how it doesn't work in order for me to fix it

IM REALLY SORRY. i digged really deep, i found the clipsvc corrupted thats why it cant trick the minecraft that i owned it. i used dism
